name: Deploy Hosting

on:
  push:
    branches: master

jobs:
  build-hosting:
    name: Build Hosting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
        env:
          NODE_ENV: development
      - name: Archive Development Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist-hosting
          path: dist
  e2e-test:
    name: e2e Test
    needs: [build-hosting]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
          start: npm run dev
          wait-on: http://localhost:5173/
        env:
          CYPRESS_baseUrl: http://localhost:5173/
  deploy-hosting:
    name: Deploy Hosting
    needs: [e2e-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist-hosting
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
